version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    groups:
      all-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
